### ISSUE TITLE
async

### ISSUE THREAD

**Issue by VB10** [mehmettalhairmak/Rick-And-Morty-iOS#1]
https://github.com/mehmettalhairmak/Rick-And-Morty-iOS/blob/7ea2fa6b698045e0c5e2a163cd512ea24dcfc780/Rick%20and%20Morty/Service/RickyMortyService.swift#L25

async await yapalım 1
path isimleri dikkat iki
birde resutl type

**Comment by mehmettalhairmak** [comment]
api servisler async/await ile değiştirilmiştir hocam. tekrardan düzeltilmesi gerekenler varsa issue birakabilirseniz çok makbule geçer ec3e571

**Comment by mehmettalhairmak** [comment]
> https://github.com/mehmettalhairmak/Rick-And-Morty-iOS/blob/7ea2fa6b698045e0c5e2a163cd512ea24dcfc780/Rick%20and%20Morty/Service/RickyMortyService.swift#L25
> 
> async await yapalım 1 path isimleri dikkat iki birde resutl type

api servisler async/await ile değiştirilmiştir hocam. tekrardan düzeltilmesi gerekenler varsa issue birakabilirseniz çok makbule geçer ec3e571

**Comment by mehmettalhairmak** [comment]
> https://github.com/mehmettalhairmak/Rick-And-Morty-iOS/blob/7ea2fa6b698045e0c5e2a163cd512ea24dcfc780/Rick%20and%20Morty/Service/RickyMortyService.swift#L25
> 
> async await yapalım 1 path isimleri dikkat iki birde resutl type

api servisler async/await ile değiştirilmiştir ve ona uygun bazı minimal değişiklikler yapılmıştır hocam. tekrardan düzeltilmesi gerekenler varsa issue birakabilirseniz çok makbule geçer hocam @VB10 https://github.com/mehmettalhairmak/Rick-And-Morty-iOS/commit/ec3e57114491e61435628f49f50da93ff48e1250
